apiVersion: apps/v1
kind: Deployment
metadata:
  name: akrobateo
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: akrobateo
  template:
    metadata:
      labels:
        name: akrobateo
    spec:
      serviceAccountName: akrobateo
      containers:
        - name: akrobateo
          image: registry.pharos.sh/kontenapharos/akrobateo:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 20M
              cpu: 100m
            limits:
              memory: 100M
              cpu: 200m
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "akrobateo"
